### ISSUE TITLE
Improving the dashboard design

### ISSUE THREAD

**Issue by kRavi07** [Grace-Rasaily780/boringfinance#2]
Improving the dashboard UI design to make it more better in terms of UI-UX and user engagement . There are few areas in which dashboard design lags and doesn't give good UI vibe and user interaction. Here are few points , I suggest for improvement .

1. Typography & Layout Enhancements
    Adjust font weights for key headings and primary information to improve visual hierarchy (e.g., "Dashboard" title, income amount).
    Increase padding and spacing between sections for better readability and a more spacious layout.
2. Using Cards to show the budegt related statistics.
3.  Using custom icons to show the transaction history.

Here is the improved design , I am suggesting, I have already done the changes. Let me know if any further improvement in this or if you like the design approve this , I will create pull request.
![boring-finance-dashboard](https://github.com/user-attachments/assets/d5f2a297-e950-4a81-aabd-3d7d1dd16deb)

**Comment by Grace-Rasaily780** [comment]
Hello @kRavi07,
Really glad to hear and look the improvement. I really appreciate your time and effort for making the project more user friendly and more interesting. Here are the things that I really loved:

1. The stats about the percentage of amount left in a specific group
2. As you said, the use of cards is brilliant
3. The icon used make it more user accessible
4. The use of colors are really commendable, although the theme is meant to be neutral and non-simulating, I love how you integrated colors in the most color neutral app (aka "Boring")

Before merging the pull request that I request you to create. Please provide more information and changes on these context, so that I can document the changes properly:
1. The mobile view - As the application is more phone focused as it is reflected on UI, please provide the info about the mobile design and responsiveness
2. The details of what changes you have actually made - I believe that you will provide those details in the PR so its just a formality
3. Your honest opinion about the app and he design, lol - I know its a bit informal about it but your insights of the previous user experience and user interface will really mean a lot to me

These are just things to keep in my documentation about the app, so feel free to skip and jump here and there. Again really glad for your insights and contribution. I am really looking forward with the PR.

Thank you,
A Wannabe 
Grace Rasaily

**Comment by kRavi07** [comment]
It will be fully responsive, need to do a little bit of more work to fix few minor things on mobile devices. I am attaching few screeenshot from mobile and tablet device. 
I have not changed much things, I have just used Card component from shadcn along with tailwind css, as we already using tailwind, we can make use of it more, instead of creating external css for every minor things.

I love your idea about the app as this is still in initial development phase but initial impression was good. I like your miniamlstic UI approach . I have lot of ideas or feature which we can incorporate to make it more better and user friendly, looking forward to have a discussion on this. I will create PR by tomorrow. 
**Mobile UI** :
![iPhone-13-PRO-boring-finance](https://github.com/user-attachments/assets/417a88b5-f95e-4bb0-b81e-728d08f06eb8)
![iPhone-13-PRO-boring-finance-2](https://github.com/user-attachments/assets/4b9d3c7b-8a16-4374-a44c-333b4c33482a)

**IPad** : 
![iPad-Mini-boring-finance](https://github.com/user-attachments/assets/fb5e304a-9750-43a1-9475-2667dbd9db53)

**Comment by Grace-Rasaily780** [comment]
@kRavi07,
Really appreciate the mobile view that you have provided. I will looking forward to the PR and surely will get these changes merged. Thank you for contribution you have made.

Thank you,
A Wannabe
Grace Rasaily
